/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license.
-/
import SternBrocot.Basic
import Mathlib.Logic.Relation

/-!
# Structure of the tail relation, and the quotient form of rigidity

`SternBrocot.Basic` proves rigidity in the form "sends tail *pairs* to tail
pairs". That is only the honest statement about the *quotient* if the
equivalence relation generated by `TailPair` is no larger than `TailPair`
itself, symmetrised and reflexivised. This file proves exactly that.

## Main results

* `SternBrocot.TailPair.left_unique` / `right_unique` — each side of a tail pair
  determines the other, and the branch point.
* `SternBrocot.not_tailPair_of_tailPair_left` — **no chains**: the right element
  of a tail pair is never the left element of another. Left elements are bounded
  above, right elements are cofinite, and no set is both.
* `SternBrocot.tailEqv_iff_eqvGen` — consequently every equivalence class has at
  most two elements: `Relation.EqvGen TailPair` is just
  `a = b ∨ TailPair a b ∨ TailPair b a`.
* `SternBrocot.rigidity` — **the rigidity theorem, quotient form**: `x ↦ x ∆ m`
  descends to `P(ω)/∼` iff `m = ∅` or `m = ω`.
-/

open Set
open scoped symmDiff

namespace SternBrocot

/-! ### Each side of a tail pair determines the other -/

/-- A tail pair has distinct sides: the branch point lies in one and not the
other. -/
theorem IsTailPairAt.ne {n : ℕ} {a b : Set ℕ} (h : IsTailPairAt n a b) : a ≠ b := by
  rintro rfl
  exact h.notMem_right h.mem_left

theorem TailPair.ne {a b : Set ℕ} (h : TailPair a b) : a ≠ b :=
  let ⟨_, h⟩ := h; h.ne

/-- The left element determines the branch point: it is the largest element. -/
theorem IsTailPairAt.branch_eq_of_left {n n' : ℕ} {a b b' : Set ℕ}
    (h : IsTailPairAt n a b) (h' : IsTailPairAt n' a b') : n = n' := by
  by_contra hne
  rcases lt_or_gt_of_ne hne with hlt | hgt
  · exact absurd h'.mem_left (h.left_top n' hlt)
  · exact absurd h.mem_left (h'.left_top n hgt)

/-- The right element determines the branch point: it is the largest element of
the complement. -/
theorem IsTailPairAt.branch_eq_of_right {n n' : ℕ} {a a' b : Set ℕ}
    (h : IsTailPairAt n a b) (h' : IsTailPairAt n' a' b) : n = n' := by
  by_contra hne
  rcases lt_or_gt_of_ne hne with hlt | hgt
  · exact h'.notMem_right (h.right_tail n' hlt)
  · exact h.notMem_right (h'.right_tail n hgt)

/-- A tail pair's left element determines its right element. -/
theorem TailPair.left_unique {a b b' : Set ℕ} (h : TailPair a b) (h' : TailPair a b') :
    b = b' := by
  obtain ⟨n, h⟩ := h
  obtain ⟨n', h'⟩ := h'
  have hnn : n = n' := h.branch_eq_of_left h'
  subst hnn
  ext k
  rcases lt_trichotomy k n with hk | rfl | hk
  · exact (h.below k hk).symm.trans (h'.below k hk)
  · simp only [iff_iff_implies_and_implies]
    exact ⟨fun hc => absurd hc h.notMem_right, fun hc => absurd hc h'.notMem_right⟩
  · exact iff_of_true (h.right_tail k hk) (h'.right_tail k hk)

/-- A tail pair's right element determines its left element. -/
theorem TailPair.right_unique {a a' b : Set ℕ} (h : TailPair a b) (h' : TailPair a' b) :
    a = a' := by
  obtain ⟨n, h⟩ := h
  obtain ⟨n', h'⟩ := h'
  have hnn : n = n' := h.branch_eq_of_right h'
  subst hnn
  ext k
  rcases lt_trichotomy k n with hk | rfl | hk
  · exact (h.below k hk).trans (h'.below k hk).symm
  · exact iff_of_true h.mem_left h'.mem_left
  · simp only [iff_iff_implies_and_implies]
    exact ⟨fun hc => absurd hc (h.left_top k hk), fun hc => absurd hc (h'.left_top k hk)⟩

/-! ### No chains

The left element of a tail pair is bounded above; the right element contains a
cofinite tail. No set is both, so tail pairs cannot be composed and every
equivalence class has at most two elements. -/

/-- A set that is bounded above and also contains everything above some point is
impossible. -/
theorem not_bddAbove_and_tail {s : Set ℕ} {n n' : ℕ}
    (hb : ∀ k, n < k → k ∉ s) (ht : ∀ k, n' < k → k ∈ s) : False := by
  have h1 : n < max n n' + 1 := by omega
  have h2 : n' < max n n' + 1 := by omega
  exact hb _ h1 (ht _ h2)

/-- **No chains, right.** If `(a, b)` is a tail pair then `b` is not the left
element of any tail pair. -/
theorem not_tailPair_of_tailPair_left {a b c : Set ℕ} (hab : TailPair a b) :
    ¬ TailPair b c := by
  rintro ⟨n', hbc⟩
  obtain ⟨n, hab⟩ := hab
  exact not_bddAbove_and_tail hbc.left_top hab.right_tail

/-- **No chains, left.** If `(a, b)` is a tail pair then `a` is not the right
element of any tail pair. -/
theorem not_tailPair_of_tailPair_right {a b c : Set ℕ} (hab : TailPair a b) :
    ¬ TailPair c a := by
  rintro ⟨n', hca⟩
  obtain ⟨n, hab⟩ := hab
  exact not_bddAbove_and_tail hab.left_top hca.right_tail

/-! ### The tail equivalence -/

/-- The tail equivalence: `a ∼ b` iff they are equal or form a tail pair in one
order or the other. By `tailEqv_iff_eqvGen` this really is the equivalence
relation generated by `TailPair`. -/
def TailEqv (a b : Set ℕ) : Prop := a = b ∨ TailPair a b ∨ TailPair b a

theorem TailEqv.refl (a : Set ℕ) : TailEqv a a := Or.inl rfl

theorem TailEqv.symm {a b : Set ℕ} : TailEqv a b → TailEqv b a := by
  rintro (rfl | h | h)
  · exact Or.inl rfl
  · exact Or.inr (Or.inr h)
  · exact Or.inr (Or.inl h)

theorem TailEqv.trans {a b c : Set ℕ} : TailEqv a b → TailEqv b c → TailEqv a c := by
  rintro (rfl | hab | hba) hbc
  · exact hbc
  · rcases hbc with (rfl | hbc | hcb)
    · exact Or.inr (Or.inl hab)
    · exact absurd hbc (not_tailPair_of_tailPair_left hab)
    · exact Or.inl (hab.right_unique hcb)
  · rcases hbc with (rfl | hbc | hcb)
    · exact Or.inr (Or.inr hba)
    · exact Or.inl (hba.left_unique hbc)
    · exact absurd hcb (not_tailPair_of_tailPair_right hba)

theorem tailEqv_equivalence : Equivalence TailEqv :=
  ⟨TailEqv.refl, TailEqv.symm, TailEqv.trans⟩

/-- The setoid on `P(ω)` given by the tail relation. -/
def tailSetoid : Setoid (Set ℕ) := ⟨TailEqv, tailEqv_equivalence⟩

/-- **Every tail class has at most two elements.** The equivalence relation
generated by `TailPair` adds nothing beyond reflexivity and symmetry. -/
theorem tailEqv_iff_eqvGen (a b : Set ℕ) :
    TailEqv a b ↔ Relation.EqvGen TailPair a b := by
  constructor
  · rintro (rfl | h | h)
    · exact Relation.EqvGen.refl _
    · exact Relation.EqvGen.rel _ _ h
    · exact Relation.EqvGen.symm _ _ (Relation.EqvGen.rel _ _ h)
  · intro h
    induction h with
    | rel _ _ h => exact Or.inr (Or.inl h)
    | refl _ => exact TailEqv.refl _
    | symm _ _ _ ih => exact ih.symm
    | trans _ _ _ _ _ ih₁ ih₂ => exact ih₁.trans ih₂

/-! ### Rigidity, quotient form -/

/-- A map descends to the tail quotient when it respects `TailEqv`. -/
def Descends (f : Set ℕ → Set ℕ) : Prop := ∀ a b, TailEqv a b → TailEqv (f a) (f b)

theorem symmDiff_left_cancel {a b m : Set ℕ} (h : a ∆ m = b ∆ m) : a = b := by
  ext k
  have := Set.ext_iff.mp h k
  simp only [Set.mem_symmDiff] at this
  by_cases hm : k ∈ m <;> tauto

/-- **The rigidity theorem, quotient form.**

For `m ⊆ ω`, the Boolean translation `x ↦ x ∆ m` descends to the tail quotient
`P(ω)/∼` if and only if `m = ∅` or `m = ω` — that is, iff it is the identity or
reciprocal.

This is the no-go theorem behind the asymmetry the construction exhibits:
reciprocal is a Boolean operation, negation becomes one only after adjoining the
sign point `ω`, and addition can never be one. -/
theorem rigidity (m : Set ℕ) : Descends (· ∆ m) ↔ m = ∅ ∨ m = univ := by
  rw [← symmDiff_preservesTail_iff]
  constructor
  · -- Descending forces tail pairs to tail pairs: equality is impossible.
    intro h a b hab
    rcases h a b (Or.inr (Or.inl hab)) with heq | hl | hr
    · exact absurd (symmDiff_left_cancel heq) hab.ne
    · exact Or.inl hl
    · exact Or.inr hr
  · intro h a b hab
    rcases hab with (rfl | hab | hba)
    · exact TailEqv.refl _
    · rcases h a b hab with hl | hr
      · exact Or.inr (Or.inl hl)
      · exact Or.inr (Or.inr hr)
    · rcases h b a hba with hl | hr
      · exact Or.inr (Or.inr hl)
      · exact Or.inr (Or.inl hr)

end SternBrocot
